install_obs:
	https://github.com/obsproject/obs-studio
config_obs:
	Server: rtmp://localhost:1935/live/test
	Stream Key: 
install_xiu:
	cargo intall xiu
start_xiu:
 	xiu -r 1935 -f 8080
watch_live:
	./live.html
