//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub mod prelude;

pub mod permission;
pub mod permission_role_map;
pub mod role;
pub mod sea_orm_active_enums;
pub mod user;
pub mod user_role_map;
