//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::permission::Entity as Permission;
pub use super::permission_role_map::Entity as PermissionRoleMap;
pub use super::role::Entity as Role;
pub use super::user::Entity as User;
pub use super::user_role_map::Entity as UserRoleMap;
