//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "userstatus")]
pub enum Userstatus {
    #[sea_orm(string_value = "Available")]
    Available,
    #[sea_orm(string_value = "Disabled")]
    Disabled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "usertype")]
pub enum Usertype {
    #[sea_orm(string_value = "Admin")]
    Admin,
    #[sea_orm(string_value = "Normal")]
    Normal,
    #[sea_orm(string_value = "SuperAdmin")]
    SuperAdmin,
}
