/*
 * demo_server_main
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileUploadReq : Just a schema for axum native multipart
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileUploadReq {
    #[serde(rename = "file")]
    pub file: std::path::PathBuf,
    #[serde(rename = "name")]
    pub name: String,
}

impl FileUploadReq {
    /// Just a schema for axum native multipart
    pub fn new(file: std::path::PathBuf, name: String) -> FileUploadReq {
        FileUploadReq {
            file,
            name,
        }
    }
}

