/*
 * demo_server_main
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileInfo {
    #[serde(rename = "content_type")]
    pub content_type: String,
    #[serde(rename = "file_name")]
    pub file_name: String,
    #[serde(rename = "size")]
    pub size: i32,
}

impl FileInfo {
    pub fn new(content_type: String, file_name: String, size: i32) -> FileInfo {
        FileInfo {
            content_type,
            file_name,
            size,
        }
    }
}

