/*
 * demo_server_main
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserType {
    #[serde(rename = "Normal")]
    Normal,
    #[serde(rename = "Admin")]
    Admin,
    #[serde(rename = "SuperAdmin")]
    SuperAdmin,

}

impl std::fmt::Display for UserType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Normal => write!(f, "Normal"),
            Self::Admin => write!(f, "Admin"),
            Self::SuperAdmin => write!(f, "SuperAdmin"),
        }
    }
}

impl Default for UserType {
    fn default() -> UserType {
        Self::Normal
    }
}

