/*
 * demo_server_main
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserUpdateReq {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "mobile", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mobile: Option<Option<String>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
}

impl UserUpdateReq {
    pub fn new(id: i64) -> UserUpdateReq {
        UserUpdateReq {
            id,
            mobile: None,
            name: None,
        }
    }
}

