/*
 * evolve_axum_new
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthorizeType {
    #[serde(rename = "User")]
    User,
    #[serde(rename = "APP")]
    App,
    #[serde(rename = "Enterprise")]
    Enterprise,

}

impl std::fmt::Display for AuthorizeType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::User => write!(f, "User"),
            Self::App => write!(f, "APP"),
            Self::Enterprise => write!(f, "Enterprise"),
        }
    }
}

impl Default for AuthorizeType {
    fn default() -> AuthorizeType {
        Self::User
    }
}

