/*
 * evolve_axum_new
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthReqAuthorizeType {
    AuthorizeType(models::AuthorizeType),
}

impl Default for AuthReqAuthorizeType {
    fn default() -> Self {
        Self::AuthorizeType(Default::default())
    }
}

