/*
 * evolve_axum_new
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MsgResp {
    #[serde(rename = "msg")]
    pub msg: String,
}

impl MsgResp {
    pub fn new(msg: String) -> MsgResp {
        MsgResp {
            msg,
        }
    }
}

