/*
 * evolve_axum_main
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSearchResp {
    #[serde(rename = "data")]
    pub data: Vec<models::SearchedUser>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl UserSearchResp {
    pub fn new(data: Vec<models::SearchedUser>, total: i32) -> UserSearchResp {
        UserSearchResp {
            data,
            total,
        }
    }
}

