apiVersion: v1
kind: Namespace
metadata:
  name: stateful

---

apiVersion: v1
kind: Secret
metadata:
  name: meilisearch-secret
  namespace: stateful
type: Opaque
stringData:
  MEILI_MASTER_KEY: "masterKey"
  
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: stateful
  name: meilisearch
spec:
  serviceName: "meilisearch"
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.0.2
          ports:
            - containerPort: 7700
          env: 
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  # 从上面创建的 Secret 中获取 root 密码
                  name: meilisearch-secret
                  key: MEILI_MASTER_KEY
          volumeMounts:
            - name: meilisearch
              mountPath: /meili_data
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1Gi"
          livenessProbe:
            tcpSocket:
              port: 7700
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 7700
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: meilisearch
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi


---

apiVersion: v1
kind: Service
metadata:
  namespace: stateful
  name: meilisearch
spec:
  type: NodePort # <--- 修改类型为 NodePort
  selector:
    app: meilisearch
  ports:
  - protocol: TCP
    port: 7700
    targetPort: 7700
    nodePort: 30705   # <--- 指定映射到节点的端口 (与 Kind 配置中的 containerPort 匹配)
