apiVersion: v1
kind: Namespace
metadata:
  name: stateful

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: stateful
data:
  redis.conf: |
    port 6379
    appendonly yes

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: stateful
  name: redis
spec:
  serviceName: "redis"
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          command: ["redis-server", "/etc/redis/redis.conf"]
          volumeMounts:
            - name: redis
              mountPath: /data
            - name: config
              mountPath: /etc/redis
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1Gi"
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: redis-config
  volumeClaimTemplates:
    - metadata:
        name: redis
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi


---

apiVersion: v1
kind: Service
metadata:
  namespace: stateful
  name: redis
spec:
  type: NodePort # <--- 修改类型为 NodePort
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30703   # <--- 指定映射到节点的端口 (与 Kind 配置中的 containerPort 匹配)
